# Overview

This notebook is to understand how the API endpoints work in the Metadata Editor and we can use the official package to do some common tasks

# Setup

In [2]:
import requests
import os
from pymetadataeditor import MetadataEditor 
import pandas as pd

In [2]:
# BASE_URL = 'https://metadataeditorqa.worldbank.org/index.php'
BASE_URL = 'https://metadataeditor.worldbank.org/index.php'
api_url = 'https://metadataeditor.worldbank.org/index.php/api' # For the package

# Define mapping for path and collection
conf_mapping = {
    "PU": ("public", 22),
    "OU": ("ouo", 820)
}

In [3]:
os.getcwd()

'c:\\WBG\\wb560793\\Data360-OpsProject\\data360_ops-wt\\metadata_editor\\notebooks\\metadata_editor'

In [4]:
# Import from token file
with open('../../me_keys.token', 'r') as file:
	api_key = file.read().strip().split('=')[1]

# Experimenting with the API

## Projects

### Search

In [5]:
collection_num = 22
type = 'timeseries'
limit = 1000  # Max limit per page
headers = {"x-api-key": api_key}

In [6]:
# request_url = f"{BASE_URL}/api/editor?collection={collection_num}&type={type}&limit={limit}&offset=0"
request_url = f"{BASE_URL}/api/editor?collection={collection_num}&type={type}&limit=10&offset=0"
response = requests.get(request_url, headers=headers)
result = response.json()

In [7]:
result

{'status': 'success',
 'total': 10139,
 'found': 10,
 'offset': 0,
 'limit': 10,
 'projects': [{'id': '25486',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '194708d0-7fd4-4ce5-9969-6b75323a73db',
   'study_idno': 'GD_WBL_SAF',
   'title': 'Women, Business and the Law: Safety Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:52:13-05:00',
   'changed': '2026-02-17T16:34:17-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25486'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25486'}]},
  {'id': '25487',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': 'c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc',
   'study_idno': 'GD_WBL_MOB',
   'title': 'Women, Business and the Law: Mobility Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:19-05:00',
   'changed': '2026-02-17T16:34:17-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25487'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25487'}]},
  {'id': '25488',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '7f2fd1fe-d811-497e-a859-ced01f37ae22',
   'study_idno': 'GD_WBL_WRK',
   'title': 'Women, Business and the Law: Work Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:17-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25488'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25488'}]},
  {'id': '25496',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': 'c44d3415-9314-4ee3-a15a-9dcd55105ad3',
   'study_idno': 'GD_WBL_OVL',
   'title': 'Women, Business and the Law: Overall Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:21-05:00',
   'changed': '2026-02-17T16:34:17-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25496'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25496'}]},
  {'id': '25492',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': 'f74f4164-46d8-4e11-b62b-d2de15290e32',
   'study_idno': 'GD_WBL_CHC',
   'title': 'Women, Business and the Law: Childcare Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:16-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25492'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25492'}]},
  {'id': '25493',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '9d36685c-7085-4e96-8610-a22711442167',
   'study_idno': 'GD_WBL_ENT',
   'title': 'Women, Business and the Law: Entrepreneurship Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:16-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25493'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25493'}]},
  {'id': '25494',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '03fede52-ea1a-4c87-b0ba-a9887e9a8221',
   'study_idno': 'GD_WBL_AST',
   'title': 'Women, Business and the Law: Assets Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:16-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25494'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25494'}]},
  {'id': '25495',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '3682dcb0-fd55-4ed6-bc89-696c44125e42',
   'study_idno': 'GD_WBL_PEN',
   'title': 'Women, Business and the Law: Pension Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:16-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25495'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25495'}]},
  {'id': '25489',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': 'e4d9e274-e45c-4077-99dc-e5210ba7c3e9',
   'study_idno': 'GD_WBL_PAY',
   'title': 'Women, Business and the Law: Pay Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:15-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25489'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25489'}]},
  {'id': '25490',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '560a45e8-a539-4fec-b9b7-7374524471d0',
   'study_idno': 'GD_WBL_MAR',
   'title': 'Women, Business and the Law: Marriage Topic',
   'abbreviation': None,
   'nation': None,
   'year_start': '2026',
   'year_end': '2026',
   'published': None,
   'created': '2026-01-28T12:53:20-05:00',
   'changed': '2026-02-17T16:34:15-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '91',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_WBL'},
   'is_locked': None,
   'username': 'srv_ddh_ops',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '22', 'title': 'Data360 - Public', 'sid': '25490'},
    {'id': '117',
     'title': 'WB_WBL: Women, Business and the Law',
     'sid': '25490'}]}],
 'filters': {'user_id': [23],
  'collection': [22],
  'exclude_collections': False,
  'type': ['timeseries']}}

In [8]:
request_url = f"{BASE_URL}/api/editor?collection=820&type={type}&limit=10&offset=0"
response = requests.get(request_url, headers=headers)
result = response.json()
result

{'status': 'success',
 'total': 4,
 'found': 4,
 'offset': 0,
 'limit': 10,
 'projects': [{'id': '25567',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': 'b7959982-3891-4b5b-87d2-3191c11c901b',
   'study_idno': 'AE_JB_EXP',
   'title': 'Export-linked employment',
   'abbreviation': None,
   'nation': None,
   'year_start': '0',
   'year_end': '0',
   'published': None,
   'created': '2026-02-03T13:01:58-05:00',
   'changed': '2026-02-04T17:44:07-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '114',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_AIE'},
   'is_locked': None,
   'username': 'Lorena Corso',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '820', 'title': 'Data360 - OU', 'sid': '25567'},
    {'id': '842', 'title': 'WB_AIE: Activities in Exports', 'sid': '25567'}]},
  {'id': '25566',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '0c481b8f-05c5-4a95-b314-4156507ada67',
   'study_idno': 'AE_INC_EXP',
   'title': 'Export income',
   'abbreviation': None,
   'nation': None,
   'year_start': '0',
   'year_end': '0',
   'published': None,
   'created': '2026-02-03T13:01:58-05:00',
   'changed': '2026-02-04T17:43:16-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '114',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WB_AIE'},
   'is_locked': None,
   'username': 'Lorena Corso',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '820', 'title': 'Data360 - OU', 'sid': '25566'},
    {'id': '842', 'title': 'WB_AIE: Activities in Exports', 'sid': '25566'}]},
  {'id': '25570',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '20350cb2-8d74-447e-a2cf-21ae26ad97bc',
   'study_idno': 'ATLAS_GNI',
   'title': 'Gross National Income',
   'abbreviation': None,
   'nation': None,
   'year_start': '0',
   'year_end': '0',
   'published': None,
   'created': '2026-02-03T13:45:02-05:00',
   'changed': '2026-02-03T13:45:02-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '4',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WBG_ICG'},
   'is_locked': None,
   'username': 'Cathrine Machingauta',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '820', 'title': 'Data360 - OU', 'sid': '25570'},
    {'id': '841',
     'title': 'WB_ICG: World Bank Group (WBG) Income Classification, ATLAS method',
     'sid': '25570'}]},
  {'id': '25561',
   'pid': None,
   'version_number': None,
   'type': 'indicator',
   'idno': '0df63c24-ff16-4970-93fe-f1d3ceb100d7',
   'study_idno': 'ATLAS_OPS_GROUP',
   'title': 'World Bank Group Operational Classification',
   'abbreviation': None,
   'nation': None,
   'year_start': '0',
   'year_end': '0',
   'published': None,
   'created': '2026-02-03T12:05:29-05:00',
   'changed': '2026-02-03T12:55:53-05:00',
   'varcount': None,
   'created_by': '4',
   'changed_by': '4',
   'is_shared': None,
   'thumbnail': None,
   'template_uid': '30ab32c7d62aa6e2801efcf336658dbb',
   'attributes': {'database_id': 'WBG_ICG'},
   'is_locked': None,
   'username': 'Cathrine Machingauta',
   'username_cr': 'Cathrine Machingauta',
   'versions': [],
   'collections': [{'id': '820', 'title': 'Data360 - OU', 'sid': '25561'},
    {'id': '841',
     'title': 'WB_ICG: World Bank Group (WBG) Income Classification, ATLAS method',
     'sid': '25561'}]}],
 'filters': {'user_id': [23],
  'collection': [820],
  'exclude_collections': False,
  'type': ['timeseries']}}

### Collections

For the publish pipeline I need to identify all the projects that have been modify in a specific time window

In [5]:
me = MetadataEditor(api_url=api_url, api_key=api_key, verify_ssl=False)

In [6]:
# List projects from collection 22 (public)
projects = me.list_projects_in_collection(collection=22, limit=10)
# projects = me.list_projects_in_collection(collection=22, limit='All')
# projects = me.list_projects_in_collection(collection=820, limit='All')
print(projects.shape)
projects

c:\WBG\wb560793\Data360-OpsProject\venv_data360_ops\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'metadataeditor.worldbank.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

(10, 25)

,pid,version_number,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,...,changed_by,is_shared,thumbnail,template_uid,attributes,is_locked,username,username_cr,versions,collections
id,,,,,,,,,,,,,,,,,,,,,
25493,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,2026,2026,...,179,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25486,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,2026,2026,...,179,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25488,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,2026,2026,...,179,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25487,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,2026,2026,...,179,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
18052,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,None,None,...,91,None,None,feb19dde1a8910d2259f307990955bcc,None,None,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25496,None,None,indicator,c44d3415-9314-4ee3-a15a-9dcd55105ad3,GD_WBL_OVL,"Women, Business and the Law: Overall Scores",None,None,2026,2026,...,91,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25495,None,None,indicator,3682dcb0-fd55-4ed6-bc89-696c44125e42,GD_WBL_PEN,"Women, Business and the Law: Pension Topic",None,None,2026,2026,...,91,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25491,None,None,indicator,dfaf67de-11e7-46a0-904f-7a383db18cbf,GD_WBL_PAR,"Women, Business and the Law: Parenthood Topic",None,None,2026,2026,...,91,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25492,None,None,indicator,f74f4164-46d8-4e11-b62b-d2de15290e32,GD_WBL_CHC,"Women, Business and the Law: Childcare Topic",None,None,2026,2026,...,91,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."
25494,None,None,indicator,03fede52-ea1a-4c87-b0ba-a9887e9a8221,GD_WBL_AST,"Women, Business and the Law: Assets Topic",None,None,2026,2026,...,91,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si..."

In [7]:
# Extract all projects from both collections and combine into a single dataframe
me_projects_df = pd.DataFrame()
for key, value in conf_mapping.items():
	conf, collection_num = value
	print(f"Extracting '{conf}' metadata projects in collection: {collection_num}")
	temp_df = me.list_projects_in_collection(collection=collection_num, limit='All')
	temp_df['obs_conf'] = key
	me_projects_df = pd.concat([me_projects_df, temp_df], ignore_index=False)
	me_projects_df.reset_index(drop=False, inplace=True)
me_projects_df

Extracting 'public' metadata projects in collection: 22
Extracting 'ouo' metadata projects in collection: 820

,index,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,...,is_shared,thumbnail,template_uid,attributes,is_locked,username,username_cr,versions,collections,obs_conf
0,0,25493.0,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU
1,1,25486.0,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU
2,2,25488.0,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU
3,3,25487.0,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU
4,4,18052.0,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,...,None,None,feb19dde1a8910d2259f307990955bcc,None,None,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10491,25566,NaN,None,None,indicator,0c481b8f-05c5-4a95-b314-4156507ada67,AE_INC_EXP,Export income,None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_AIE'},None,Lorena Corso,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU
10492,25563,NaN,None,None,indicator-db,d11e0e65-2c85-43e3-9734-67f0840561cc,WB_AIE,Activities in Exports,None,None,...,None,None,,None,None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU
10493,25570,NaN,None,None,indicator,20350cb2-8d74-447e-a2cf-21ae26ad97bc,ATLAS_GNI,Gross National Income,None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WBG_ICG'},None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU
10494,25561,NaN,None,None,indicator,0df63c24-ff16-4970-93fe-f1d3ceb100d7,ATLAS_OPS_GROUP,World Bank Group Operational Classification,None,None,...,None,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WBG_ICG'},None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU
10495,25503,NaN,None,None,indicator-db,2e64ebbe-4548-4bde-a71d-7800ae3cfe6c,WBG_ICG,"World Bank Group (WBG) Lending Thresholds, Atl...",None,None,...,None,None,timeseries-db-system-en,None,None,echoliu,echoliu,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU

In [8]:
# Check unique values in attributes column
me_projects_df['attributes'].apply(lambda x: list(x.keys()) if x is not None else []).explode().unique()

array(['database_id', nan], dtype=object)

In [ ]:
# Extract dataset_id from attributes column
def extract_value_from_key(dictionary, key='database_id'):
	if dictionary is not None and key in dictionary:
		return dictionary[key]
	return None

me_projects_df['dataset_id'] = me_projects_df['attributes'].apply(lambda x: extract_value_from_key(x, 'database_id'))
me_projects_df

,index,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,...,thumbnail,template_uid,attributes,is_locked,username,username_cr,versions,collections,obs_conf,dataset_id
0,0,25493.0,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL
1,1,25486.0,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL
2,2,25488.0,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL
3,3,25487.0,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL
4,4,18052.0,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,...,None,feb19dde1a8910d2259f307990955bcc,None,None,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10491,25566,NaN,None,None,indicator,0c481b8f-05c5-4a95-b314-4156507ada67,AE_INC_EXP,Export income,None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_AIE'},None,Lorena Corso,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WB_AIE
10492,25563,NaN,None,None,indicator-db,d11e0e65-2c85-43e3-9734-67f0840561cc,WB_AIE,Activities in Exports,None,None,...,None,,None,None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,None
10493,25570,NaN,None,None,indicator,20350cb2-8d74-447e-a2cf-21ae26ad97bc,ATLAS_GNI,Gross National Income,None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WBG_ICG'},None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WBG_ICG
10494,25561,NaN,None,None,indicator,0df63c24-ff16-4970-93fe-f1d3ceb100d7,ATLAS_OPS_GROUP,World Bank Group Operational Classification,None,None,...,None,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WBG_ICG'},None,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WBG_ICG
10495,25503,NaN,None,None,indicator-db,2e64ebbe-4548-4bde-a71d-7800ae3cfe6c,WBG_ICG,"World Bank Group (WBG) Lending Thresholds, Atl...",None,None,...,None,timeseries-db-system-en,None,None,echoliu,echoliu,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,None

In [10]:
# Transform created and changed columns to datetime with timezone into account
me_projects_df['created_utc'] = pd.to_datetime(me_projects_df['created'], utc=True)
me_projects_df['changed_utc'] = pd.to_datetime(me_projects_df['changed'], utc=True)
# Ignore hour from created and changed columns
me_projects_df['created_utc_date'] = me_projects_df['created_utc'].dt.normalize()
me_projects_df['changed_utc_date'] = me_projects_df['changed_utc'].dt.normalize()

me_projects_df

,index,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,...,username,username_cr,versions,collections,obs_conf,dataset_id,created_utc,changed_utc,created_utc_date,changed_utc_date
0,0,25493.0,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 21:09:05+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
1,1,25486.0,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:52:13+00:00,2026-02-18 21:06:14+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
2,2,25488.0,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 21:03:18+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
3,3,25487.0,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:19+00:00,2026-02-18 20:55:33+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
4,4,18052.0,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,...,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,None,2025-02-26 21:09:47+00:00,2026-02-18 20:53:02+00:00,2025-02-26 00:00:00+00:00,2026-02-18 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10491,25566,NaN,None,None,indicator,0c481b8f-05c5-4a95-b314-4156507ada67,AE_INC_EXP,Export income,None,None,...,Lorena Corso,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WB_AIE,2026-02-03 18:01:58+00:00,2026-02-04 22:43:16+00:00,2026-02-03 00:00:00+00:00,2026-02-04 00:00:00+00:00
10492,25563,NaN,None,None,indicator-db,d11e0e65-2c85-43e3-9734-67f0840561cc,WB_AIE,Activities in Exports,None,None,...,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,None,2026-02-03 18:01:57+00:00,2026-02-03 19:17:55+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10493,25570,NaN,None,None,indicator,20350cb2-8d74-447e-a2cf-21ae26ad97bc,ATLAS_GNI,Gross National Income,None,None,...,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WBG_ICG,2026-02-03 18:45:02+00:00,2026-02-03 18:45:02+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10494,25561,NaN,None,None,indicator,0df63c24-ff16-4970-93fe-f1d3ceb100d7,ATLAS_OPS_GROUP,World Bank Group Operational Classification,None,None,...,Cathrine Machingauta,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,WBG_ICG,2026-02-03 17:05:29+00:00,2026-02-03 17:55:53+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10495,25503,NaN,None,None,indicator-db,2e64ebbe-4548-4bde-a71d-7800ae3cfe6c,WBG_ICG,"World Bank Group (WBG) Lending Thresholds, Atl...",None,None,...,echoliu,echoliu,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",OU,None,2026-01-29 19:48:27+00:00,2026-01-29 19:54:02+00:00,2026-01-29 00:00:00+00:00,2026-01-29 00:00:00+00:00

In [ ]:
# me_projects_df.to_csv('me_projects.csv', index=False)

In [11]:
## Filter dataframe when changed2 date is between a given start and end date
start_date = pd.Timestamp('2026-02-10', tz='UTC')
end_date = pd.Timestamp('2026-02-17', tz='UTC')
filtered_projects_range = me_projects_df[
    (me_projects_df['changed_utc_date'] >= start_date) & 
    (me_projects_df['changed_utc_date'] <= end_date)].copy()
print(filtered_projects_range['changed_utc_date'].unique())
print(filtered_projects_range.shape)
filtered_projects_range

<DatetimeArray>
['2026-02-12 00:00:00+00:00', '2026-02-11 00:00:00+00:00',
 '2026-02-10 00:00:00+00:00']
Length: 3, dtype: datetime64[ns, UTC]
(87, 33)

,index,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,...,username,username_cr,versions,collections,obs_conf,dataset_id,created_utc,changed_utc,created_utc_date,changed_utc_date
14,14,18165.0,None,None,timeseries-db,a5ec5ad3-e4f0-4d0e-a3ad-e056952769a3,WB_WITS,World Integrated Trade Solution (WITS),None,None,...,srv_ddh_ops,srv_ddh_ops,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,None,2025-02-26 21:12:59+00:00,2026-02-12 19:15:44+00:00,2025-02-26 00:00:00+00:00,2026-02-12 00:00:00+00:00
15,15,7159.0,None,None,timeseries,d2c1f1be-4e5c-4446-b6e4-7499586eb3c9,WB_WITS_NMBR_XPRT_HS6_PRDCT,Exports - Number of traded HS6 digit Products,None,None,...,srv_ddh_ops,Sinae Lee,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WITS,2024-06-26 18:56:39+00:00,2026-02-12 19:15:39+00:00,2024-06-26 00:00:00+00:00,2026-02-12 00:00:00+00:00
16,16,7158.0,None,None,timeseries,0599a3c6-c7f0-4584-a9f8-6a0cde46c31f,WB_WITS_NMBR_MPRT_HS6_PRDCT,Imports - Number of traded HS6 digit Products,None,None,...,srv_ddh_ops,Sinae Lee,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WITS,2024-06-26 18:56:39+00:00,2026-02-12 19:15:38+00:00,2024-06-26 00:00:00+00:00,2026-02-12 00:00:00+00:00
17,17,7160.0,None,None,timeseries,3212b22c-5651-4767-814d-712ae6945430,WB_WITS_NMBR_XPRT_PRTNR,Number of export partners,None,None,...,srv_ddh_ops,Sinae Lee,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WITS,2024-06-26 18:56:39+00:00,2026-02-12 19:15:38+00:00,2024-06-26 00:00:00+00:00,2026-02-12 00:00:00+00:00
18,18,7161.0,None,None,timeseries,71eb302f-3fbe-40fe-834f-500568e6cbce,WB_WITS_NMBR_MPRT_PRTNR,Number of import partners,None,None,...,srv_ddh_ops,Sinae Lee,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WITS,2024-06-26 18:56:39+00:00,2026-02-12 19:15:38+00:00,2024-06-26 00:00:00+00:00,2026-02-12 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,5592.0,None,None,timeseries,2d8e6ea1-4847-44ed-b39c-6638a3911c5b,ID_OWN_BRTH,Birth Certification,None,None,...,srv_ddh_ops,echoliu,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_ID4D,2024-06-12 17:41:39+00:00,2026-02-10 10:22:49+00:00,2024-06-12 00:00:00+00:00,2026-02-10 00:00:00+00:00
97,97,24349.0,None,None,timeseries,ebcf70d1-823f-41a4-b5a8-82c2a37b8136,E_ID_USED,Online digital ID has been used on phone or co...,None,None,...,srv_ddh_ops,echoliu,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_ID4D,2025-10-24 18:48:24+00:00,2026-02-10 10:22:48+00:00,2025-10-24 00:00:00+00:00,2026-02-10 00:00:00+00:00
98,98,24350.0,None,None,timeseries,2319f59f-b607-4d4e-8638-bc63d353f57c,ID_MISUSE,Foundational ID has been used without permissi...,None,None,...,srv_ddh_ops,echoliu,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_ID4D,2025-10-24 18:49:07+00:00,2026-02-10 10:22:48+00:00,2025-10-24 00:00:00+00:00,2026-02-10 00:00:00+00:00
99,99,24352.0,None,None,timeseries,b27ec45c-f1ce-44ca-9071-f5e52838537e,NOID_S,Population without an ID by reason,None,None,...,srv_ddh_ops,echoliu,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_ID4D,2025-10-24 18:50:47+00:00,2026-02-10 10:22:48+00:00,2025-10-24 00:00:00+00:00,2026-02-10 00:00:00+00:00
100,100,5589.0,None,None,timeseries,bb231526-0f92-4f17-bb72-802245ada3b5,ID_OWN,ID ownership,None,None,...,srv_ddh_ops,echoliu,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_ID4D,2024-06-12 17:41:39+00:00,2026-02-10 10:22:48+00:00,2024-06-12 00:00:00+00:00,2026-02-10 00:00:00+00:00

In [15]:
today = pd.Timestamp.today()

In [22]:
## Filter dataframe when changed2 date is between a given start and end date
today = pd.Timestamp.today()
start_date = pd.Timestamp((today - pd.Timedelta(days=1)).normalize(), tz='UTC')
end_date = pd.Timestamp((today + pd.Timedelta(days=1)).normalize(), tz='UTC')
filtered_projects_range = me_projects_df[
    (me_projects_df['changed_utc_date'] >= start_date) & 
    (me_projects_df['changed_utc_date'] <= end_date)].copy()
print(filtered_projects_range['changed_utc_date'].unique())
print(filtered_projects_range.shape)
filtered_projects_range

<DatetimeArray>
['2026-02-18 00:00:00+00:00']
Length: 1, dtype: datetime64[ns, UTC]
(14, 33)

,index,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,...,username,username_cr,versions,collections,obs_conf,dataset_id,created_utc,changed_utc,created_utc_date,changed_utc_date
0,0,25493.0,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 21:09:05+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
1,1,25486.0,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:52:13+00:00,2026-02-18 21:06:14+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
2,2,25488.0,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 21:03:18+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
3,3,25487.0,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,...,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:19+00:00,2026-02-18 20:55:33+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
4,4,18052.0,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,...,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,None,2025-02-26 21:09:47+00:00,2026-02-18 20:53:02+00:00,2025-02-26 00:00:00+00:00,2026-02-18 00:00:00+00:00
5,5,25496.0,None,None,indicator,c44d3415-9314-4ee3-a15a-9dcd55105ad3,GD_WBL_OVL,"Women, Business and the Law: Overall Scores",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:21+00:00,2026-02-18 20:52:58+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
6,6,25495.0,None,None,indicator,3682dcb0-fd55-4ed6-bc89-696c44125e42,GD_WBL_PEN,"Women, Business and the Law: Pension Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:57+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
7,7,25491.0,None,None,indicator,dfaf67de-11e7-46a0-904f-7a383db18cbf,GD_WBL_PAR,"Women, Business and the Law: Parenthood Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:56+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
8,8,25492.0,None,None,indicator,f74f4164-46d8-4e11-b62b-d2de15290e32,GD_WBL_CHC,"Women, Business and the Law: Childcare Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:56+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
9,9,25494.0,None,None,indicator,03fede52-ea1a-4c87-b0ba-a9887e9a8221,GD_WBL_AST,"Women, Business and the Law: Assets Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:56+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
10,10,25489.0,None,None,indicator,e4d9e274-e45c-4077-99dc-e5210ba7c3e9,GD_WBL_PAY,"Women, Business and the Law: Pay Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:55+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
11,11,25490.0,None,None,indicator,560a45e8-a539-4fec-b9b7-7374524471d0,GD_WBL_MAR,"Women, Business and the Law: Marriage Topic",None,None,...,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,WB_WBL,2026-01-28 17:53:20+00:00,2026-02-18 20:52:55+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
12,12,25651.0,None,None,indicator-db,0b9f0915-62ed-4924-ba7f-4d2063665b38,DHS_SD,Survey Based Indicators,None,None,...,srv_ddh_ops,srv_ddh_ops,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,None,2026-02-18 20:46:45+00:00,2026-02-18 20:46:45+00:00,2026-02-18 00:00:00+00:00,2026-02-18 00:00:00+00:00
13,13,25650.0,None,None,indicator,3cfc83a9-efb2-4700-ac79-96b75946eb69,RH_ANCC_W_IRN,Percentage of women with a live birth (or stil...,None,None,...,srv_ddh_ops,srv_ddh_ops,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",PU,DHS_SD,2026-02-18 20:46:41+00:00,2026-02-18 20:46:41+00:00,2026-02-18 00:00:00+00:00,2026-02-18 00:00:00+00:00

In [23]:
print(today)
print(start_date)
print(end_date)

2026-02-18 16:14:54.899771
2026-02-17 00:00:00+00:00
2026-02-19 00:00:00+00:00

# Developing functions for production

## extract_value_from_key

This function should go in utils

In [26]:
# Extract value from a key in a dictionary 
def extract_value_from_key(dictionary, key='database_id'):
	if dictionary is not None and key in dictionary:
		return dictionary[key]
	return None

In [ ]:
# temp = projects.copy()

In [ ]:
# temp['dataset_id'] = temp['attributes'].apply(lambda x: extract_value_from_key(x, 'database_id'))
# temp['collection_id'] = 22
# temp['collection_title'] = temp['collections'].apply(lambda x: next((extract_value_from_key(item, 'title') for item in x if item['id'] == '22'), None))
# temp

,pid,version_number,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,...,template_uid,attributes,is_locked,username,username_cr,versions,collections,dataset_id,collection_id,collection_title
id,,,,,,,,,,,,,,,,,,,,,
25493,None,None,indicator,9d36685c-7085-4e96-8610-a22711442167,GD_WBL_ENT,"Women, Business and the Law: Entrepreneurship ...",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25486,None,None,indicator,194708d0-7fd4-4ce5-9969-6b75323a73db,GD_WBL_SAF,"Women, Business and the Law: Safety Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25488,None,None,indicator,7f2fd1fe-d811-497e-a859-ced01f37ae22,GD_WBL_WRK,"Women, Business and the Law: Work Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25487,None,None,indicator,c7bccfad-6d1e-4fb2-9f75-c7e9ffae44bc,GD_WBL_MOB,"Women, Business and the Law: Mobility Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,Viktoriia-Anna Oliinyk,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
18052,None,None,timeseries-db,778b8a90-2fad-4483-ac5d-bbd96bd5bd0d,WB_WBL,"Women, Business and the Law (WBL)",None,None,None,None,...,feb19dde1a8910d2259f307990955bcc,None,None,srv_ddh_ops,Gaurav Bhardwaj,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",None,22,Data360 - Public
25496,None,None,indicator,c44d3415-9314-4ee3-a15a-9dcd55105ad3,GD_WBL_OVL,"Women, Business and the Law: Overall Scores",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25495,None,None,indicator,3682dcb0-fd55-4ed6-bc89-696c44125e42,GD_WBL_PEN,"Women, Business and the Law: Pension Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25491,None,None,indicator,dfaf67de-11e7-46a0-904f-7a383db18cbf,GD_WBL_PAR,"Women, Business and the Law: Parenthood Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25492,None,None,indicator,f74f4164-46d8-4e11-b62b-d2de15290e32,GD_WBL_CHC,"Women, Business and the Law: Childcare Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public
25494,None,None,indicator,03fede52-ea1a-4c87-b0ba-a9887e9a8221,GD_WBL_AST,"Women, Business and the Law: Assets Topic",None,None,2026,2026,...,30ab32c7d62aa6e2801efcf336658dbb,{'database_id': 'WB_WBL'},None,srv_ddh_ops,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public

## get_projects_from_collection

In [ ]:
def get_projects_from_collection(
        api_key: str,
        api_url: str='https://metadataeditor.worldbank.org/index.php/api',
        collections: int|list=[22,820]
    ) -> pd.DataFrame:
	"""Function to get projects from a list of collections and return a combined dataframe with additional columns
	
	Args:
		api_key (str): API key for authentication.
		api_url (str): The base URL of the API. 
		collections (int|list): A single collection number or a list of collection numbers to extract projects from. Defaults to [22, 820].
	returns:
		pd.DataFrame: A combined dataframe with projects from all specified collections, including additional columns for confidentiality and dataset_id.
	"""
	# Transform collections to list if it's a single integer
	if isinstance(collections, int):
		collections = [collections]

	# Initialize MetadataEditor instance
	me = MetadataEditor(api_url=api_url, api_key=api_key, verify_ssl=False)

	# Initialize an empty dataframe to store combined projects
	me_projects_df = pd.DataFrame()

	# Extract all projects from both collections and combine into a single dataframe
	for col in collections:
		print(f"Extracting metadata projects in collection: {col}")
		temp_df = me.list_projects_in_collection(collection=col, limit='All')
		# Extract information from columns with dictionaries
		temp_df['dataset_id'] = temp_df['attributes'].apply(
			lambda x: extract_value_from_key(x, 'database_id'))
		temp_df['collection_id'] = col
		temp_df['collection_title'] = temp_df['collections'].\
			apply(lambda x: next(
				(extract_value_from_key(item, 'title') for item in x 
	 				if item['id'] == str(col)), None))
		# Transform created and changed columns to datetime with timezone into account
		temp_df['created_utc'] = pd.to_datetime(temp_df['created'], utc=True)
		temp_df['changed_utc'] = pd.to_datetime(temp_df['changed'], utc=True)
		# Ignore hour from created and changed columns
		temp_df['created_utc_date'] = temp_df['created_utc'].dt.normalize() #type: ignore
		temp_df['changed_utc_date'] = temp_df['changed_utc'].dt.normalize() #type: ignore
		# Concatenate to main dataframe
		me_projects_df = pd.concat([me_projects_df, temp_df], ignore_index=False)
	
	# Reset index after concatenation
	me_projects_df.reset_index(drop=False, inplace=True)

	return me_projects_df

In [43]:
projects_df = get_projects_from_collection(
    api_key=api_key, 
    api_url=api_url, 
    collections=[22, 820]
)
projects_df

Extracting metadata projects in collection: 22
Extracting metadata projects in collection: 820

,id,pid,version_number,type,idno,study_idno,title,abbreviation,nation,year_start,...,username_cr,versions,collections,dataset_id,collection_id,collection_title,created_utc,changed_utc,created_utc_date,changed_utc_date
0,25653,None,None,indicator-db,25f94dee-31e0-4cd3-a80b-be92cad18c55,WB_AGGCRS,Development finance aggregates from OECD CRS F...,None,None,None,...,srv_ddh_ops,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",None,22,Data360 - Public,2026-02-18 21:40:24+00:00,2026-02-18 21:40:24+00:00,2026-02-18 00:00:00+00:00,2026-02-18 00:00:00+00:00
1,25652,None,None,indicator,21afb906-c262-47c3-b696-f119dea11b13,FN_AID_DEV,Total financial inflows from donors,None,None,1973,...,srv_ddh_ops,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_AGGCRS,22,Data360 - Public,2026-02-18 21:40:20+00:00,2026-02-18 21:40:20+00:00,2026-02-18 00:00:00+00:00,2026-02-18 00:00:00+00:00
2,25489,None,None,indicator,e4d9e274-e45c-4077-99dc-e5210ba7c3e9,GD_WBL_PAY,"Women, Business and the Law: Pay Topic",None,None,2026,...,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public,2026-01-28 17:53:20+00:00,2026-02-18 21:28:29+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
3,25492,None,None,indicator,f74f4164-46d8-4e11-b62b-d2de15290e32,GD_WBL_CHC,"Women, Business and the Law: Childcare Topic",None,None,2026,...,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public,2026-01-28 17:53:20+00:00,2026-02-18 21:26:07+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
4,25491,None,None,indicator,dfaf67de-11e7-46a0-904f-7a383db18cbf,GD_WBL_PAR,"Women, Business and the Law: Parenthood Topic",None,None,2026,...,Cathrine Machingauta,[],"[{'id': '22', 'title': 'Data360 - Public', 'si...",WB_WBL,22,Data360 - Public,2026-01-28 17:53:20+00:00,2026-02-18 21:24:25+00:00,2026-01-28 00:00:00+00:00,2026-02-18 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10493,25566,None,None,indicator,0c481b8f-05c5-4a95-b314-4156507ada67,AE_INC_EXP,Export income,None,None,0,...,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",WB_AIE,820,Data360 - OU,2026-02-03 18:01:58+00:00,2026-02-04 22:43:16+00:00,2026-02-03 00:00:00+00:00,2026-02-04 00:00:00+00:00
10494,25563,None,None,indicator-db,d11e0e65-2c85-43e3-9734-67f0840561cc,WB_AIE,Activities in Exports,None,None,None,...,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",None,820,Data360 - OU,2026-02-03 18:01:57+00:00,2026-02-03 19:17:55+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10495,25570,None,None,indicator,20350cb2-8d74-447e-a2cf-21ae26ad97bc,ATLAS_GNI,Gross National Income,None,None,0,...,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",WBG_ICG,820,Data360 - OU,2026-02-03 18:45:02+00:00,2026-02-03 18:45:02+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10496,25561,None,None,indicator,0df63c24-ff16-4970-93fe-f1d3ceb100d7,ATLAS_OPS_GROUP,World Bank Group Operational Classification,None,None,0,...,Cathrine Machingauta,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",WBG_ICG,820,Data360 - OU,2026-02-03 17:05:29+00:00,2026-02-03 17:55:53+00:00,2026-02-03 00:00:00+00:00,2026-02-03 00:00:00+00:00
10497,25503,None,None,indicator-db,2e64ebbe-4548-4bde-a71d-7800ae3cfe6c,WBG_ICG,"World Bank Group (WBG) Lending Thresholds, Atl...",None,None,None,...,echoliu,[],"[{'id': '820', 'title': 'Data360 - OU', 'sid':...",None,820,Data360 - OU,2026-01-29 19:48:27+00:00,2026-01-29 19:54:02+00:00,2026-01-29 00:00:00+00:00,2026-01-29 00:00:00+00:00

## filter_projects_by_changed_date

In [1]:
def filter_projects_by_changed_date(
		projects_df: pd.DataFrame,
		start_date: str,
		end_date: str) -> pd.DataFrame:
	"""Filter projects dataframe based on a date range for the changed_utc_date column.
	If start_date and end_date are empty, this function will return projects modified in the last 48 hours.

	The reason for using last 48 hours instead of last 24 hours is to account for any timezone differences and ensure we capture all projects modified "today" in any timezone.

	Args:
		projects_df (pd.DataFrame): DataFrame containing projects with a 'changed_utc_date' column.
		start_date (str): Start date in 'YYYY-MM-DD' format.
		end_date (str): End date in 'YYYY-MM-DD' format.

	Returns:
		pd.DataFrame: Filtered DataFrame containing projects where 'changed_utc_date' is between the specified start and end dates.
	"""
	# Set start and end dates as timestamps with timezone
	today = pd.Timestamp.today()
	if start_date is None:
		# Set start_date to 48 hours ago to account for timezone differences and ensure we capture all projects modified "today" in any timezone
		starting_date = pd.Timestamp((today - pd.Timedelta(days=1)).normalize(), tz='UTC')
	else:
		starting_date = pd.Timestamp(start_date, tz='UTC')

	if end_date is None:
		ending_date = pd.Timestamp((today + pd.Timedelta(days=1)).normalize(), tz='UTC')
	else:
		ending_date = pd.Timestamp(end_date, tz='UTC')

	filtered_projects_range = projects_df[
		(projects_df['changed_utc_date'] >= starting_date) & 
		(projects_df['changed_utc_date'] <= ending_date)].copy()
	
	return filtered_projects_range

NameError: name 'pd' is not defined